// More .NET IoT Samples here:
// * https://github.com/microsoft/Windows-iotcore-samples
// * https://github.com/dotnet/iot

using System;
using System.Device.Spi;
using System.Drawing;
using Iot.Device.Ws28xx;

// This code sample uses C# 9's Top Level Statements feature.
// A Main method is generated by the compiler for us.
// Learn more: https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements

static int GetLedCount() {
    int count;
    if (!int.TryParse(Environment.GetEnvironmentVariable("LED_COUNT"), out count)) {
        // If we fail to parse the number of LED's or it is undefined set to 1 so we still attempt to light something.
        // If you're running this and 1 LED is always lighting up make sure LED_COUNT is set in your env.
        Console.WriteLine("⚠ LED_COUNT was not found or couldn't be parsed.");
        count = 1;
    }
    return count;
}

// Limit a value to between a minimum and maximum value
// This can prevent out of bounds indexes on the strip
static int Clamp(int value, int min, int max) {
    if (value > max) {
        return max;
    } else if (value < min) {
        return min;
    } else {
        return value;
    }
}

var ledCount = GetLedCount();
Console.WriteLine($"Coloring {ledCount} LEDs...");

var connectionSettings = new SpiConnectionSettings(0, 0) {
    ClockFrequency = 2400000,
    Mode = SpiMode.Mode0,
    DataBitLength = 8,
    
};

// Create an SPI device based on the current operating system.
// For Raspbian this should be a UnixSpiDevice.
var spiDevice = SpiDevice.Create(connectionSettings);
// Ws2812b is the spec for the type of lights we are using.
// The device we create is how we communicate with our LED's
var device = new Ws2812b(spiDevice, ledCount);
var image = device.Image;

var direction = 1;
var position = 0;

while(true)
{
    // Clear the previous state.
    image.Clear(Color.DarkBlue);
    // Add a tail to the initial position
    image.SetPixel(Clamp(position - direction * 2, 0, ledCount - 1), 0, Color.Blue);
    image.SetPixel(Clamp(position - direction, 0, ledCount - 1), 0, Color.Cyan);
    image.SetPixel(position, 0, Color.White);
    device.Update(); // Actually update the LED strip
    System.Threading.Thread.Sleep(50);

    // Move our position
    position += direction;
    if (direction < 0 && position <= 0) {
        position = 0;
        direction = 1;
    } else if (direction > 0 && position >= ledCount - 1) {
        position = ledCount - 1;
        direction = -1;
    }
}